### ISSUE TITLE
Reference` to non-existent field `'gamma'

### ISSUE THREAD

**Issue by shaokunzhao** [CIC-methods/FID-A#105] opened 2023-03-01 14:26 UTC
Hello, I'm having trouble generating the basis set for the PR-STEAM sequence when running the "run_simExampleBasisSet.m" program. Can you please help me troubleshoot this error? Thank you.

Reference` to non-existent field `'gamma'.

Error in op_complexConj (line 30)
ppm = -f/(in.Bo*in.gamma);

Error in io_writelcmraw (line 40)
data_struct=op_complexConj(data_struct);

Error in sim_lcmrawbasis (line 112)
    RF=io_writelcmraw(out,[metab '.RAW'],metab);

Error in run_simExampleBasisSet (line 65)
    [RF,H2O]=sim_lcmrawbasis(np,sw,Bo,lb,'H2O',te1,te2,ref,'y',seq);

**Comment by basab-gupta** [comment] 2023-04-16 10:05
Hi @shaokunzhao,

I am having the same issue when I run `run_simExampleBasisSet.m`. I tried looking into the documentation, but can't seem to figure out what gamma is.  I was wondering if you were able to find a solution to this issue?

**Comment by basab-gupta** [comment] 2023-04-16 14:40
Okay, so upon going through the other run scripts in the repo, I realized that gamma is most probably the [gyromagentic ratio](https://en.wikipedia.org/wiki/Gyromagnetic_ratio).

@jamienear I think the issue is that the struct passed to the function in `op_complexConj.m` does not have any fields for the nucleus type and the gamma so it throws an error.

**Comment by jamienear** [comment] 2023-07-17 19:21
So sorry for the long delay in responding.  I think this issues should be fixed now, thanks to a recent pull request from Peter Truong.  Please let me know if the issue persists.

**Closed by jamienear** 2023-07-17 19:21 UTC
